BaseUrl: "https://lacnotredame.org/"
ContentDir: "content"
LayoutDir: "layouts"
PublishDir: "public"
BuildDrafts: true
languageCode: "en-us"
Title: "Lac Notre-Dame and Usher Lake Association"
PluralizeListTitles: False
googleAnalytics: ""
menu:
 
Params:
  Author: ""
  Banner: ""
  DateForm: "2006-01-02"
  disqusShortname: ""
  Search: ""
  ShowRelatedPost: True
  Slogan: ""
taxonomies:
  tag: "tags"
permalinks:
  post: /post/:year/:slug/
MetadataFormat: "yaml"
theme: "bootstrapfour"
sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"